### ISSUE TITLE
Deprecation Notice: 

### ISSUE THREAD

**Issue by tfMovamo** [sudiptpa/guid#29]
Deprecation Notice: Class Sujip\Guid\Facades\Guid located in ./vendor/sudiptpa/guid/src/Sujip/Guid/Facades/Guid.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///home/vagrant/projects/icatched/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Sujip\Guid\Guid located in ./vendor/sudiptpa/guid/src/Sujip/Guid/Guid.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///home/vagrant/projects/icatched/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Sujip\Guid\GuidServiceProvider located in ./vendor/sudiptpa/guid/src/Sujip/Guid/GuidServiceProvider.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0

**Comment by sudiptpa** [comment]
@tfMovamo give a little run down on how to recreate this issue. If you know the solution feel free to submit a PR.

**Comment by sudiptpa** [comment]
Fixed #31
